// <auto-generated />
namespace RegistryManagmentV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_strings_to_nvarchar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_strings_to_nvarchar));
        
        string IMigrationMetadata.Id
        {
            get { return "201803140249162_change_strings_to_nvarchar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
