// <auto-generated />
namespace RegistryManagmentV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Extend_resource_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Extend_resource_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201803181342449_Extend_resource_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
