// <auto-generated />
namespace RegistryManagmentV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migrate_on_independent_association : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrate_on_independent_association));
        
        string IMigrationMetadata.Id
        {
            get { return "201803181717329_Migrate_on_independent_association"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
